### ISSUE TITLE
TypeError: canvas.getContext is not a function

### ISSUE THREAD

**Issue by eric2788** [Kokoro-js/koishi-plugin-word-cloud#1]
使用时发生未知错误。
日志如下:
```java
2023-11-01 09:45:33 [W] command cloud 
                        TypeError: canvas.getContext is not a function
                            at getMinFontSize (/koishi/node_modules/koishi-plugin-word-cloud/lib/wordcloud.js:12:24)
                            at module.exports (/koishi/node_modules/koishi-plugin-word-cloud/lib/wordcloud.js:36:5)
                            at _Command.<anonymous> (/koishi/node_modules/koishi-plugin-word-cloud/lib/index.js:97:58)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1331:14)
                            at async _Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1346:22)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2175:22
                            at async _Session.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:2077:22)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:1053:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:1053:16)
```

插件信息:
![image](https://github.com/Kokoro-js/koishi-plugin-word-cloud/assets/6276840/5e75959e-9f95-43cb-accd-6b63e82b8d2e)

koishi版本: v4.15.3

**Comment by ahdg6** [comment]
看看你的skia-canvas

**Comment by eric2788** [comment]
> 看看你的skia-canvas

![image](https://github.com/Kokoro-js/koishi-plugin-word-cloud/assets/6276840/f5ce9cec-8ca1-4897-92e0-783b8c6d73f8)
要看啥

配置是

/data/canvas
/data/canvas/font

**Comment by ahdg6** [comment]
只在4.15.0+出现吗

**Comment by ahdg6** [comment]
canvas的那个testcherrybox的指令你跑一下看看

**Comment by eric2788** [comment]
> 只在4.15.0+出现吗

这个就不知道了

**Comment by eric2788** [comment]
> canvas的那个testcherrybox的指令你跑一下看看

![image](https://github.com/Kokoro-js/koishi-plugin-word-cloud/assets/6276840/b1a8b659-4d00-4fb0-8c44-8667a62bec91)

**Comment by eric2788** [comment]
好像还伴随了这个错误，不知关联否

![image](https://github.com/Kokoro-js/koishi-plugin-word-cloud/assets/6276840/904e5b0d-a37f-46b8-a3e4-43c2c9e0b9e1)

```java
2023-11-01 14:04:29 [W] console ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '; SELECT count(distinct `id`) AS value FROM (SELECT `id`, `platform`, `flag`,...' at line 1
                            at _MySQLDriver.query (/koishi/node_modules/@minatojs/driver-mysql/lib/index.js:354:19)
                            at _MySQLDriver._flushTasks (/koishi/node_modules/@minatojs/driver-mysql/lib/index.js:387:32)
                            at /koishi/node_modules/@minatojs/driver-mysql/lib/index.js:378:35
                            at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
2023-11-01 14:04:30 [W] console ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '; SELECT count(distinct `id`) AS value FROM (SELECT `id`, `platform`, `flag`,...' at line 1
                            at _MySQLDriver.query (/koishi/node_modules/@minatojs/driver-mysql/lib/index.js:354:19)
                            at _MySQLDriver._flushTasks (/koishi/node_modules/@minatojs/driver-mysql/lib/index.js:387:32)
                            at /koishi/node_modules/@minatojs/driver-mysql/lib/index.js:378:35
                            at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by ahdg6** [comment]
![图片](https://github.com/Kokoro-js/koishi-plugin-word-cloud/assets/36436808/e2637bf2-0b2e-4136-aea6-16783ea60be0)
![图片](https://github.com/Kokoro-js/koishi-plugin-word-cloud/assets/36436808/ea937ec8-f5a0-4c8d-890d-05e785a6b62d)
这三个相关插件我都没适配 4.15.0+，到时候我测试看看

**Comment by ahdg6** [comment]
0.4.4 好了
